metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['localhost:9100']
    remote_write:
      - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        basic_auth:
          username: 1026925
          password: glc_eyJvIjoiODczNjc2IiwibiI6InRlc3p0LXRva2VuZW0iLCJrIjoiWDdvV3RNaHYwODdQUzlpZTIyM1M2azVtIiwibSI6eyJyIjoiZXUifX0=
