apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: 50m
        gke-gcsfuse/memory-limit: 100Mi
    spec:
      serviceAccountName: wordpress-sa
      automountServiceAccountToken: true     
      containers:
        - name: wordpress
          image: europe-central2-docker.pkg.dev/proud-voice-386015/wp-costume/wp:1.0
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-proxy-service
            - name: WORDPRESS_DB_USER
              value: worpdress-gsa
            - name: WORDPRESS_DB_PASSWORD
              value: ""
            - name: WORDPRESS_DB_NAME
              value: wordpress-db
          volumeMounts:
            - name: gcs-volume
              mountPath: /var/www/html/wp-content/uploads
            - mountPath: /usr/local/etc/php/conf.d/valami.ini
              name: config
              readOnly: true
              subPath: valami.ini
      volumes:
        - name: cloudsql-instance-credentials
          emptyDir: {}
        - name: gcs-volume
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: wp-datas
              mountOptions: "implicit-dirs,uid=33,gid=33"
        - name: config
          configMap:
            name: php-config
            items:
            - key: valami.ini
              path: valami.ini
