apiVersion: v1
kind: Secret
metadata:
  name: primary-credentials-logs
  namespace: monitoring
stringData:
  username: '616069'
  password: 'glc_eyJvIjoiODczNjc2IiwibiI6InRlc3p0IiwiayI6IkxUUTQ3UDFzN2hsMTlyYTk2NHVzd0E4QyIsIm0iOnsiciI6ImV1In19'
